import { MD3LightTheme, MD3DarkTheme, adaptNavigationTheme } from 'react-native-paper';
import { lightColors, darkColors } from './colors';

export const paperLightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: lightColors.primary,
    primaryContainer: lightColors.primaryLight,
    onPrimary: '#FFFFFF',
    onPrimaryContainer: lightColors.primaryDark,
    secondary: lightColors.textSecondary,
    secondaryContainer: lightColors.secondaryBackground,
    onSecondary: '#FFFFFF',
    onSecondaryContainer: lightColors.textPrimary,
    tertiary: lightColors.primary,
    tertiaryContainer: lightColors.secondaryBackground,
    onTertiary: '#FFFFFF',
    onTertiaryContainer: lightColors.textPrimary,
    background: lightColors.background,
    onBackground: lightColors.textPrimary,
    surface: lightColors.card,
    onSurface: lightColors.textPrimary,
    surfaceVariant: lightColors.secondaryBackground,
    onSurfaceVariant: lightColors.textSecondary,
    error: lightColors.danger,
    onError: '#FFFFFF',
    errorContainer: lightColors.danger,
    onErrorContainer: '#FFFFFF',
    outline: lightColors.border,
    outlineVariant: lightColors.border,
    shadow: lightColors.textPrimary,
    scrim: lightColors.overlay,
    inverseSurface: lightColors.textPrimary,
    inverseOnSurface: lightColors.background,
    inversePrimary: lightColors.primary,
  },
};

export const paperDarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkColors.primary,
    primaryContainer: darkColors.primaryDark,
    onPrimary: '#FFFFFF',
    onPrimaryContainer: darkColors.primaryLight,
    secondary: darkColors.textSecondary,
    secondaryContainer: darkColors.secondaryBackground,
    onSecondary: '#FFFFFF',
    onSecondaryContainer: darkColors.textPrimary,
    tertiary: darkColors.primary,
    tertiaryContainer: darkColors.secondaryBackground,
    onTertiary: '#FFFFFF',
    onTertiaryContainer: darkColors.textPrimary,
    background: darkColors.background,
    onBackground: darkColors.textPrimary,
    surface: darkColors.card,
    onSurface: darkColors.textPrimary,
    surfaceVariant: darkColors.secondaryBackground,
    onSurfaceVariant: darkColors.textSecondary,
    error: darkColors.danger,
    onError: '#FFFFFF',
    errorContainer: darkColors.danger,
    onErrorContainer: '#FFFFFF',
    outline: darkColors.border,
    outlineVariant: darkColors.border,
    shadow: darkColors.textPrimary,
    scrim: darkColors.overlay,
    inverseSurface: darkColors.textPrimary,
    inverseOnSurface: darkColors.background,
    inversePrimary: darkColors.primary,
  },
};
